### ISSUE TITLE
No applicable version

### ISSUE THREAD

**Issue by danhanly** [adamquaile/behat-command-runner-extension#1]
`composer require --dev "adamquaile/behat-command-runner-extension *@dev"`

The above code in your readme does not resolve to an applicable version.

I've tried with numerous different stability settings but no matter what I try, I get the following message:

```
Problem 1
    - The requested package adamquaile/behat-command-runner-extension could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
```

**Comment by adamquaile** [comment]
You're right.. I wrote that before I'd actually submitted it to packagist. I've just submitted it now. 

Thanks for pointing it out.
